# Generated by Django 3.1.2 on 2020-10-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpensesApp', '0003_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
