# Generated by Django 3.1.2 on 2020-10-23 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpensesApp', '0005_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExpensesApp.profile'),
        ),
    ]
