# Generated by Django 3.1.2 on 2020-10-24 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpensesApp', '0012_auto_20201024_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpensesApp.profile'),
        ),
    ]
