# Generated by Django 3.1.2 on 2020-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201012_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='test',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
